-- Creator Space Fort Wayne — Creator Directory
-- Run this in the Supabase SQL Editor (https://eymjahxzesuoahpwzifq.supabase.co)

-- ── Schema ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS creators (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  first_name    TEXT,
  last_name     TEXT,
  email         TEXT,
  social        TEXT,
  company       TEXT,
  job_title     TEXT,
  skills        TEXT,
  created_at    TIMESTAMPTZ DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE creators ENABLE ROW LEVEL SECURITY;

-- Public read access (anyone can browse the directory)
CREATE POLICY "Public read access" ON creators
  FOR SELECT USING (true);

-- Only authenticated users can insert (for the signup form later)
CREATE POLICY "Authenticated insert" ON creators
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- ── Seed Data ───────────────────────────────────────────────────────────────

INSERT INTO creators (first_name, last_name, email, social, company, job_title, skills) VALUES
('Zach', 'Vessels', 'zach@topspheremedia.com', '@topspheremedia / @zvessels55', 'TopSphere Media', 'Videographer', 'Video Production, Editing, Drone, Color, Marketing'),
('Michael', 'Overbeck', 'michael.overbeck@outlook.com', NULL, 'Studio Science', 'Project Manager', 'Graphic Design, Brand, Video Production, Photo'),
('Lucid', NULL, 'dartalacrity@gmail.com', '@hatelucid', 'Gravity', NULL, 'Graphic Design, Brand, Video Production, Photo'),
('Jordan', 'Bentz', 'Bentz.jordan@gmail.com', '@bentzfilmz', 'Bentz Filmz', 'Videographer', 'Video, Music, Photo, Color, Social media promotion'),
('Kai', NULL, 'kylahmc@gmail.com', '@kylahmariee', NULL, NULL, 'Writer, Photo Editing, Vocalist, Creator'),
('Tee', 'Bibby', '219-487-8262', '@TeeBibbyVisuals', 'TeeBibby Visuals', 'Videographer', 'Video Production'),
('Drew', NULL, 'nxvyblxe@gmail.com', '@nxvyblxe', NULL, 'Artist', 'Artist, Producer, Sound Engineer'),
('Clarence', 'White', 'keepyourdreamalive1@gmail.com', '@K.Y.D.A_Creations', 'k.y.d.a', 'CEO', 'Photography, Video Production, 360 Booth, Social Media Management'),
('Amber', 'Reid', 'storiestoldbyar@gmail.com', '@storiestoldbyar @thelocalarchive @theamberreid', 'Stories Told By AR / The Local Archive', 'Photographer / Co-owner', 'Photography, Media Production, Directing, Acting, Vocal Coaching, Vocal Performance'),
('J.', 'Tubbs', 'iamjtubbs@gmail.com', '@IAmJTubbs', 'YM3 Music Group LLC', 'Artist/Producer/DJ', 'Music and Entertainment'),
('Kent', 'Jakway', 'gwensdad2003@gmail.com', '@gwensdad', NULL, NULL, '3D Printing, Camera Work, Connecting, Podcasting'),
('Michael', 'Banks', 'AppleOrchardKnewz@gmail.com', 'AppleOrchardKnewz/Youtube', 'AppleOrchardKnewz', 'Creator', 'DJ/Radio Host/Podcast/Video Blog'),
('Ethan', 'Kesar', 'Ethan@goldentoucan.video', '@goldentoucan.video', 'Golden Toucan', 'Videographer', 'Social Media Video Production, Brand Videos, Branded Content Creation'),
('Damionne', 'Nichols', 'marquisdamionne@gmail.com', NULL, 'TooNineteen', 'Visionary', 'Artist, Producer, Sound Engineer, Designer, Videographer'),
('Robert', 'Collie', 'rtcollie@gmail.com', NULL, NULL, NULL, 'Video Production, Writing'),
('Michael', 'Floyd', 'studiomikefloyd@hotmail.com', NULL, NULL, 'Voice Actor/Filmmaker', 'Voice Overs, Film Making'),
('Max', 'Wells', 'max4thepeople@gmail.com', '@max4thepeople', 'Max Wells', 'Artist/Producer', 'Song Writing, Mixing/Mastering, Recording Artist'),
('Adrien', 'Gentie', 'contact.gentiemedia@gmail.com', '@gentie.media', 'Gentie Media Group', 'Videographer', 'Video Production, Social Media Content'),
('Aaren', 'Neely', 'aaren@cvrkle.media', '@cvrkle', 'CVRKLE', 'Creative Director', 'Corporate / Creative Media, Audio Everything, Visual Artist'),
('Will', 'Beamon', 'rockethillproductions@gmail.com', NULL, 'Rocket Hill Productions', 'Founder', 'All Aspects of Film Production'),
('Derek', 'Hockemeyer', 'derek@sunspacestudios.com', '@sunspacestudios', 'Sunspace Studios', 'Founder', 'Creative Director / Cinematographer'),
('Dan', 'Holmes', 'danholmesfilm@gmail.com', NULL, 'DH Photo & Film', NULL, 'Director, Producer, Writer, Editor, Photographer'),
('Noah', 'Kilby', 'Noarkilby@gmail.com', '@nrkilby', 'Rune Model Management', 'Model', 'Modeling, Slaying'),
('Mitchell', 'Julian', 'Mitchell-Julian@outlook.com', '@mitchell__Julian', NULL, 'Bassist', 'Acting, Bass'),
('Miguel', 'Hernandez', 'miguel@sudnimpactgym.com', '@curlytheceo', 'Sud''n Impact Gym', 'Co-owner', 'Video Production, Editing, Business & Networking, Martial Arts, Dance'),
('Ben', 'Crane', 'crane.benjamindavid@gmail.com', '@thatbencrane', 'Brotherhood Mutual', 'Video Production Spec.', 'Directing, Cinematography, Editing, Color, Visual Effects'),
('Evan', 'Mower', 'evan@evmoproductions.com', '@evmopro', 'EvMo Productions', 'Owner', 'Video Production, Shooting, Editing'),
('Korion', 'Johnson', 'Korion923@gmail.com', NULL, NULL, NULL, 'Sports guy who likes watching cool stuff sometimes + Purdue Econ student'),
('Brandon', 'Joshua', 'bjrproductions23@gmail.com', '@bjrproductions', NULL, NULL, 'Writer, Actor, Director'),
('Michael', 'O''Connor', 'michael@fretlessstudios.com', '@fretless_studios @mike_o.connor', 'Fretless Studios', 'Owner', 'Pro Audio (Specialty Mixing, Mastering)'),
('Meghan', 'Short', 'moonlitdesignco@gmail.com', NULL, 'Moonlit Design Co', 'Owner / Designer', 'Modern Calligraphy, Event Planning, Program Management, Social Media Marketing, Budgeting'),
('Judy', 'Filler', 'judyfiller@msn.com', NULL, 'ONEHOPE Wine', 'Senior Cause Entrepreneur', 'Beverage Industry'),
('Desaray', 'Bradley', 'mistiquecreative.md@gmail.com', NULL, 'Mistique Creative', 'CEO + Creative Director', 'Storytelling, Artist, Marketing'),
('Zach', 'Ruble', 'zlruble@gmail.com', NULL, NULL, NULL, 'Producer, Director, DP, Editor'),
('Kylah', 'Carter', 'kylahmc@gmail.com', NULL, NULL, NULL, 'Writing, Singing, Creating, Painting, Dancing'),
('Daniel', 'Carpenter', 'dnlcarpentermovies@gmail.com', '@danielcarpenterfilms', NULL, NULL, 'Producer, Writing, Director, Film Editing, Visual Effects, Marketing/Branding, Photography'),
('Kayla', 'Sprayue', 'kaylasprayue@gmail.com', '@kaylasprayla', 'Concordia High School', 'Media Arts Teacher', 'Video Production, Photography, Producing, Video Editing, Documentary Film'),
('Paul', 'Harris-Arzate', 'pjha1998@gmail.com', NULL, 'Naturedudemedia', NULL, 'Drone'),
('Kara', 'Metzler', 'karahackett@gmail.com', '@thelocalfortwayne', 'The Local', 'Writer/Journalist/Editor', 'Copy Writing, Editing, Journalism, Storytelling'),
('Samantha', 'Ryan', 'RAWstudios44@gmail.com', '@RAWstudios44', 'RAW Studios', 'Director, Writer, Actress', 'Director, Writer, Photographer, Creator'),
('Mike', 'Metzler', 'mike@v1postproduction.com', 'v1postproduction.com', 'V1 Post Production', 'Editor', 'Editing'),
('Colin', 'Madden', 'colinrichardmadden@gmail.com', '@cm.indd', 'M260 Studios LLC & Purdue Fort Wayne', 'Owner/Lead Creative', 'Graphic Design, Branding, Event Photography, Art Direction, Print Design, Advertising, Typography'),
('Lauren', 'Arnold', 'larnold486@gmail.com', '@larndog_3.2983467', 'PBS Fort Wayne', 'Education Outreach Manager', 'Independent Producing, Community Outreach, Arts Advocate, Healing Arts'),
('Hannah', 'Bond', 'dancingspoon13@gmail.com', '@hannah13bond', NULL, 'Dancing Artist', 'Dance'),
('Brittany', 'Smith', 'editor@inputfortwayne.com', NULL, 'Input Fort Wayne', 'Managing Editor', 'Storytelling, Journalism, Editing, Photography'),
('Bianca', 'Beatz', 'bbtheliaison@gmail.com', '@kitchen_witch_creatrix', NULL, 'Digital Creator', 'Passionate Hispanic Home Cook, Studying Herbalism, Wild Crafter, Spice Maker'),
('Christopher', 'Symonds', NULL, NULL, 'Vision Studios LLC', 'Owner', 'Videography, Photography, Video Editing, Website Creation and Hosting, Mobile App Development, Software Developer'),
('Josh', 'Francis', 'freedomworkshop2002@protonmail.com', NULL, 'Freedom Workshop', NULL, 'Woodworking, Custom Furniture'),
('Chris', 'Lash', 'calash517@gmail.com', '@lyrically_Dope_shit', NULL, NULL, 'Song/Lyric Writing, Performing, Music Consulting'),
('Brenden', 'Clifford', 'processhiphop@gmail.com', '@cessraps', NULL, NULL, 'Song/Lyric Writing, Performing, Music Consulting'),
('Toni', 'Irby', 'toni.irby@yahoo.com', '@stylezbytoni', 'Upgrade Hair Salon / Custom Glory Wigs LLC', 'Owner/Cosmetologist', 'Owner, Model, Hairstylist, Wig Designer, Content Creator'),
('Ryan', 'Bertsch', 'rbertsch24@gmail.com', '@ryanbertsch_', NULL, NULL, 'Music Producer/Rapper/Videographer'),
('Jamarion', 'Woods', 'jamariondw23@gmail.com', 'IG&TikTok: thetreehouseisloading', NULL, NULL, 'Poet, Writer, Musical Artist'),
('Martin', 'Vazquez', 'anterovazquez2004@yahoo.com', 'IG & TikTok: MXARTINII', NULL, NULL, 'Painter, Digital Artist'),
('Naylon', 'Thompson', 'naylon.thompson@yahoo.com', 'IG: naylondion TikTok: txentogi', NULL, NULL, 'Painter, Digital Artist'),
('Craig', 'Nix', 'cnix1066@yahoo.com', NULL, NULL, NULL, 'Writing'),
('Lwin', 'Aung', 'lwinmaprod@gmail.com', 'IG: @bylwinma', NULL, NULL, 'Videographer/Photography'),
('Brandon', 'Hedges', 'bhedges1377@gmail.com', 'IG: @brandonjhedges', 'Count Your Blessings (CYB)', 'Director, Videographer', 'Directing, Videography, Photography, Acting, Music Production, Art Direction'),
('Keith', 'Hutson', 'keithmhutson@gmail.com', NULL, NULL, 'Videographer/Photography', 'B-Roll, Documentary Style, Event Photography'),
('Zion', 'Fikes', 'Zionfikes@gmail.com', 'IG: zzonxille', NULL, 'Photography', 'Model, Photography'),
('Kyle', 'Ratayczak', 'KRatayczak@gmail.com', '@KRatayczak', NULL, 'Audio Engineer/Musician', 'Audio/Music Engineering/Mixing/Mastering, Musician'),
('Brianna', 'Datta-Barrow', 'datta.brianna@gmail.com', 'IG: bdattaphotography', 'Fort Wayne Media Collaborative & Purdue Fort Wayne', 'Videographer/Photography', 'Digital Media Coordinator, Segment Producer, Podcast Host, Videographer/Photographer'),
('Zach', 'Bernard', 'zachbernard@gmail.com', NULL, '89.1 WBOI', 'Program Director', 'Audio Editing, Story Writing, Copy Editing, Audio Production'),
('Jessica', 'Moore', 'jessicamoore.des@gmail.com', '@jess.moore_23', NULL, 'Designer/Placemaking', 'Community Development, Ceramics, Placemaking Design, Event Planning'),
('Yiska', 'Trujillo', 'yiskamarthaphotography@gmail.com', '@yiskamarthaphotography', 'Yiska Martha Photography', 'Photographer', 'Photography'),
('Rachel', 'Edwards', 'rachelruth.co@gmail.com', '@rachelruth.co & @fortflowers.co', 'Fort Flowers & RachelRuth.co', 'Dried Flower Preservation', 'Custom Dried Flower Arrangement / Wedding Photographer'),
('Nick', 'Rice', 'nickrice0218@gmail.com', '@red_door_radio', 'Red Door Radio', NULL, 'Audio Production, Tracking, Mixing, Live In-Studio Performance Videos'),
('Jason', 'Mann', 'jmann68@comcast.net', 'J Michael Photography', 'J Michael Photography, LLC', 'Photographer, Videographer', 'Photography, Video, Studio Photography, Gear Junkies'),
('Maria', 'Davis', 'folia.nova.211@gmail.com', NULL, 'Folia Nova', 'Arts, Graphics, Consulting', 'Graphic Design, Digital Art, Community Development'),
('Daniel', 'Moreno', 'info@goldengreensoapcompany.com', '@goldengreensoapco', 'Golden Green Soap Company', 'Owner/Bath and Body', 'Artist, Handcrafting'),
('David', 'Stillson', 'davidstillson@gmail.com', NULL, 'Millennial Creative', NULL, 'Musician, Film Maker, Programmer, Wood Worker'),
('Aajha', 'Canton', 'aajhacanton101@gmail.com', NULL, NULL, NULL, 'Acting, Painting, Creative Writing, Modeling'),
('Troyce', 'Grant', 'troycec28@gmail.com', NULL, NULL, NULL, 'News Reporter, Model, Freelance Writing'),
('Natasha', 'Leland', 'natashaleland2000@gmail.com', 'Instagram: @tashaheartsbooks', NULL, 'Bookstagram Influencer', 'Avid Reader, Marketing and Comms Professional'),
('McKayla', 'Nevers', 'nvrsmc.photography@gmail.com', NULL, 'Never Creative LLC', 'Creative', 'Photography, Videography, Audio Mixing'),
('Sara', 'Epple', 'abovethebestrentals@gmail.com', NULL, 'Above the Best Rentals', NULL, 'Events'),
('Shantel', 'Lahr', 'shantel.lahr@gmail.com', NULL, 'In 2 the Night Events', 'Founder/CEO', 'Events, Wedding, Coordinating, Design, Creative, Leadership'),
('Peter', 'MacDonald', 'peter@macdonaldair.com', NULL, 'MacDonald Air', NULL, 'Jet Charter Booking'),
('Isaac', 'Koehlinger', 'ikoeh@icloud.com', NULL, 'Board Origins', NULL, 'Board Game Designer'),
('David', 'Wonderly', 'david@opendarkwing.com', '@opendarkwing', 'OpenDarkmedia LLC', NULL, 'Photography, Video Editing, Writing, Podcasting'),
('Tony', 'Bottone', 'Tony@creativetonemedia.com', '@tony_bottone', 'Creative Tone Media', 'Owner', 'Social Media Marketing/Content Creation'),
('Jarod', 'Davis', 'jarodbdavis@gmail.com', 'IG: jdoesthings_ / jarodbdavis.com', NULL, 'Videographer', 'Video Production, Editing, and Social Media'),
('Andy', 'Plank', 'Plankmediaftw@gmail.com', '@Not_a_camera_guy', 'Plank Media', NULL, 'Camera Operator, DP, Audio, Editor'),
('Sandy', 'Cabada', 'sandmariajunior@gmail.com', '@sanditacabada', 'Urbanworld Film Festival', 'Senior Programmer and Producer', 'Screenwriter, Film Programmer/Curator and Producer, Storytelling, Directing, Acting'),
('Caleb', 'Miller', 'mcaleb432@gmail.com', 'syd_the_kid40', NULL, 'Writer/Director', 'Writing Films, Directing'),
('Brad', 'Bores', 'bradbores@gmail.com', '@bradboresfilms', 'Brad Bores Films LLC', 'Video Creator', 'Filmmaking, Documentary, Corporate'),
('Ahmed', 'Tabron', 'Medtabrontattoos@gmail.com', 'Medtabrontattoos', 'Med Tabron Tattoos', 'Tattoo Business Owner', 'Mixed Media Painting, Digital Art, Tattooing'),
('Jillian', 'Lee', 'Jillianlee@uniqueleecreations.com', 'Instagram.com/uniqueleecreations', 'UniqueLee Creations', NULL, 'Content Creator, Bling Artist'),
('Nicolette', 'Johnson', 'nicolettejohnsonartist@gmail.com', '@nicolettejohnsonart', 'www.nicolettejohnsonart.com', 'Oil Painter', 'Oil Painting'),
('Nancy', 'Fritz', 'nancy@fritzstudiofw.com', '@fritzstudiofw', 'Fritz Studio', 'Artist/Designer/Owner', 'Oil Painting, Encaustic Painting, Laser Cut/Engraved Jewelry Design'),
('Manda', 'Jacobson', 'manda@rumblonde.studio', NULL, 'Rum Blonde Studio', 'Founder + Creative Director', 'Branding, Web Design, Marketing and Content Strategy, Digital Marketing'),
('Eric', 'Fruit', 'ericfruit8@gmail.com', '@ericfruit', 'Room 42 [21Grams]', 'Motion Designer & Video Editor', 'Cinematography, Video Editing, Animation, 3D, Video Production'),
('Ella Marie', 'Gage', 'Ellagage23@gmail.com', '@Elladoes_art', NULL, NULL, 'Acrylic Painting and Painting on Clothes and Shoes'),
('Nick', 'Kindle', 'Fineemberfilms@gmail.com', '@fineember_films', 'Fine Ember LLC', 'Videographer/Filmmaker', 'Video Editing, Video Production, Filmmaking, Art, Content Creation, Event Videography, Entrepreneurship'),
('Maddie', 'Miller', 'maddie@maddiemillerstudio.com', NULL, 'Maddie Miller Studio', 'Founder, Artist, Digital Marketing Strategist', 'Digital Marketing, Social Media Marketing, Content Marketing, Copywriting, UX Writing'),
('Callie', 'Swangin', 'callieswangin@gmail.com', 'call.me.cals_ / appleseed_studios', 'Appleseed Studios', 'Character Artist/Project Manager/Producer', 'Animation and Film Industry, Production-Oriented'),
('Molly', 'Conner', 'molly@sonderdigitalmarketing.com', NULL, 'Sonder Creative Content', NULL, 'Writer & Digital Storyteller'),
('Amelia', 'Cisna', 'Ameliacisnamedia@gmail.com', '@ameliamcisna', 'Last Shot Entertainment', 'Executive Producer', 'Film and Television, Producing, Screenwriting, Location Sound Mixing, Post-Production Sound'),
('Zion', 'Omari', 'Zionomari@artsaturated.com', 'Zionomari.260', 'Sweet Dreams / artsaturated', 'Creative Director', 'Art, Music, Dance, Recording Engineer, Videographer/Photographer, Rapper, Live Beat Making, Event Planning, Art Gallery/Vendor Curator, Dance Instructor'),
('Olivia', 'Chappell', 'oliviachappell1804@gmail.com', NULL, NULL, 'Graphic Designer', 'Graphic Design, Brand Identity, UX Design'),
('Robin', 'Atkins', 'intothewildgardendesigns@gmail.com', NULL, 'Into The Wild Garden Designs', 'Owner/Designer', 'Environmentally Friendly Garden Design, Hobbit Houses, Native Pollinators, Fairy Gardens'),
('Robin', 'Atkins', 'outofthestorybook@gmail.com', NULL, 'Out of the Storybook Photography', 'Owner/Photographer/Storycreator', 'Story Telling Photography, Cosplay, Costume/Prop Making'),
('Joseph', 'Brennan', 'josephbren@gmail.com', '@joeybren', NULL, NULL, 'Product Photography, Models, Stock Photography, Architectural'),
('Alex', 'Schultz', 'alexroyschultz@gmail.com', '@alexschultz4444', NULL, NULL, 'Actor, Writer, Director, Poet'),
('Genevieve', 'Gutzwiller', 'Info.hazeleye@gmail.com', 'IG: Hazel.eye.productions', 'Hazel Eye Productions', 'Wedding Videographers', 'Wedding Day Videography'),
('RK', 'Peroza', 'indescribablechannel@gmail.com', '@RKPeroza', 'The Indescribable Channel', 'Showrunner', 'Directing, Prop Making, Acting, Script Writing, Editing, Content Creation'),
('Devin', 'Wolfenberger', 'dswolfenberger@gmail.com', '@devinxwolf', 'W&W Digital Agency', 'Co-Founder/UX/UI Engineer', 'UX/UI Design, Wireframing, Prototyping, Usability Testing, Design Systems, SEO, HTML, CSS, JavaScript, PHP'),
('Tyler', 'Veit', 'Tyler.veit17@gmail.com', 'tylerveit_', 'Summit City Climbing Co.', 'Creative Director', 'Videography, Photography, Audio Engineering, Digital Marketing, Banjo'),
('Corbin', 'Veltum', 'corbinveltum@gmail.com', '@djcorbycorbz', 'Veltum Productions', 'Videographer/Photographer', 'Video, Photo, Editing, Lighting, Directing, Producing'),
('Cole', 'Marcuccilli', 'cole@sweetdreamsmusic.com', 'cole.marcu', 'Sweet Dreams', 'Developer', 'Drone Pilot, Programmer, Consultant'),
('Julia', 'Nicholas', 'julianicholas.business@gmail.com', 'IG: snappedbyjuls', 'Snapped By Juls', 'Owner / Freelance', 'Photography, Social Media, Marketing, Community Outreach, Music'),
('Jeff', 'Jones', 'OfficialPRSSR@yahoo.com', 'IG: OfficialPRSSR', 'No Disrespect with Villz and PRSSR', 'Music Artist, Promoter, Podcast Host/Owner', 'Songwriting, Creative Design, Poetry, Podcasting, Clothing Design, Logo Creation, Performing Arts'),
('Candace', 'Nelson', 'Bonbonsita260@yahoo.com', 'IG: @bonbonsita260', NULL, NULL, 'UGC Content Creator, Influencer, Blog, Product Testing, Beauty/Wellness, Fashion, Lifestyle'),
('Liz', 'Salser', 'Mudkind.studio@gmail.com', '@mudkind.studio', 'Mudkind Studio', 'Independent Artist & Educator', 'Ceramics, Stained Glass, Fused Jewelry, Watercolor, Oil, Acrylic, Sewing, Visual Creativity & Design Thinking'),
('Elijah', 'Conley', 'Conles01@icloud.com', 'in.royaltydesigns / edgystudio', NULL, 'Interior Designer', 'Interior Design and Sales Rep for Concrete Design'),
('Ryan', 'Peroza', 'indescribablechannel@gmail.com', '@RKPeroza', 'The Indescribable Channel', 'Showrunner', 'Directing, Prop Making, Acting, Script Writing, Editing, Content Creation');
